### ISSUE TITLE
Unable to destroy activity runtime exception

### ISSUE THREAD

**Issue by engrtitus** [Mobeye/react-native-mobeye-geolocation#25]
Hi. Thanks for this great library.

Discovered this issue via sentry

Unable to destroy activity {app.bundle.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.mobeye.geolocation.MobeyeLocationCheck@b9268f6

**Comment by engrtitus** [comment]
Thanks @PABourdais . Do you mind if i send a PR  ?..I think it could be fixed by wrapping mReactContext.unregisterReceiver(mLocationProviderReceiver) in MobeyeGeolocationModule.java in a try catch block

**Comment by AlexUzan** [comment]
Sure please do !

**Comment by engrtitus** [comment]
@AlexUzan  Done. https://github.com/Mobeye/react-native-mobeye-geolocation/pull/26

**Comment by AlexUzan** [comment]
Thank you !
I have merged it and will include it in the next release (1.3.2)
I am closing this issue now
